version = 1

[[annotations]]
path = "**/*.md"
SPDX-FileCopyrightText = "2025 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "**/*.txt"
SPDX-FileCopyrightText = "2025 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "**/*.patch"
SPDX-FileCopyrightText = "2025 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "**/*.json"
SPDX-FileCopyrightText = "2025 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "**/*.tensor"
SPDX-FileCopyrightText = "2025 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "**/*.tflite"
SPDX-FileCopyrightText = "2025 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "src_GAP/src/networks/YOLOv5/generated*/**.c"
SPDX-FileCopyrightText = "2017 GreenWaves Technologies"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "src_GAP/src/networks/YOLOv5/generated*/**.h"
SPDX-FileCopyrightText = "2017 GreenWaves Technologies"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "src_GAP/networks/YOLOv5/input_images_HeadCount/**.jpg"
SPDX-FileCopyrightText = "2025 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "src_GAP/src/networks/YOLOv5/generated*/**.bin"
SPDX-FileCopyrightText = "2023 Carlos Alberto Castro Zuleta"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "**/*.ipynb"
SPDX-FileCopyrightText = "2025 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**/*.pdf"
SPDX-FileCopyrightText = "2025 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "**/*.png"
SPDX-FileCopyrightText = "2025 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"